server:
  port: 8079

eureka:
    instance:
      instance-id: ${spring.application.name}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST

      routes:
        - id: projects
          uri: lb://projects
          predicates:
            - Path=/projects/**
